// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF7_CYmKnyD804L-z7dOJb1uLCFYskwZc',
    appId: '1:30536906711:web:d09e7beececc6655267d92',
    messagingSenderId: '30536906711',
    projectId: 'flutter-practice-e7ef2',
    authDomain: 'flutter-practice-e7ef2.firebaseapp.com',
    storageBucket: 'flutter-practice-e7ef2.firebasestorage.app',
    measurementId: 'G-XCH335GFP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvIE8WftqzNHSjOvsY08JdM_DGYtX3uXg',
    appId: '1:30536906711:android:c22291b9cfb6cbf0267d92',
    messagingSenderId: '30536906711',
    projectId: 'flutter-practice-e7ef2',
    storageBucket: 'flutter-practice-e7ef2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCew5VvKjQBg5s3FURfiquxEyG_uONZwg4',
    appId: '1:30536906711:ios:710703e39b346daa267d92',
    messagingSenderId: '30536906711',
    projectId: 'flutter-practice-e7ef2',
    storageBucket: 'flutter-practice-e7ef2.firebasestorage.app',
    iosClientId: '30536906711-pc7haekmafrsvjic0h7uurkg8b08nd87.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCew5VvKjQBg5s3FURfiquxEyG_uONZwg4',
    appId: '1:30536906711:ios:710703e39b346daa267d92',
    messagingSenderId: '30536906711',
    projectId: 'flutter-practice-e7ef2',
    storageBucket: 'flutter-practice-e7ef2.firebasestorage.app',
    iosClientId: '30536906711-pc7haekmafrsvjic0h7uurkg8b08nd87.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF7_CYmKnyD804L-z7dOJb1uLCFYskwZc',
    appId: '1:30536906711:web:653511f0d2d5007c267d92',
    messagingSenderId: '30536906711',
    projectId: 'flutter-practice-e7ef2',
    authDomain: 'flutter-practice-e7ef2.firebaseapp.com',
    storageBucket: 'flutter-practice-e7ef2.firebasestorage.app',
    measurementId: 'G-1V6TQNEK96',
  );
}
